"""change tag 2

Revision ID: 4414e7b5a5c7
Revises: 48537f96fdd2
Create Date: 2024-03-26 23:49:58.744416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4414e7b5a5c7'
down_revision: Union[str, None] = '48537f96fdd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_post_id_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'post_id')
    op.alter_column('users', 'user_role',
               existing_type=postgresql.ENUM('admin', 'moderator', 'user', name='user_role'),
               type_=sa.Enum('admin', 'moderator', 'user', name='user_role'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_role',
               existing_type=sa.Enum('admin', 'moderator', 'user', name='user_role'),
               type_=postgresql.ENUM('admin', 'moderator', 'user', name='user_role'),
               existing_nullable=True)
    op.add_column('tags', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_post_id_fkey', 'tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
