"""change tag

Revision ID: 48537f96fdd2
Revises: 32230e568a67
Create Date: 2024-03-26 23:39:08.919103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48537f96fdd2'
down_revision: Union[str, None] = '32230e568a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('tags_user_id_fkey', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tags', 'user_id')
    op.alter_column('users', 'user_role',
               existing_type=postgresql.ENUM('admin', 'moderator', 'user', name='user_role'),
               type_=sa.Enum('admin', 'moderator', 'user', name='user_role'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_role',
               existing_type=sa.Enum('admin', 'moderator', 'user', name='user_role'),
               type_=postgresql.ENUM('admin', 'moderator', 'user', name='user_role'),
               existing_nullable=True)
    op.add_column('tags', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key('tags_user_id_fkey', 'tags', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tags', 'post_id')
    # ### end Alembic commands ###
