"""add blacklist token

Revision ID: b7a04d79844f
Revises: 3892e708026a
Create Date: 2024-03-29 21:42:46.924680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7a04d79844f'
down_revision: Union[str, None] = '3892e708026a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.alter_column('users', 'user_role',
               existing_type=postgresql.ENUM('admin', 'moderator', 'user', name='user_role'),
               type_=sa.Enum('admin', 'moderator', 'user', name='user_role'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_role',
               existing_type=sa.Enum('admin', 'moderator', 'user', name='user_role'),
               type_=postgresql.ENUM('admin', 'moderator', 'user', name='user_role'),
               existing_nullable=True)
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
